#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=pi@airq.local
readonly TARGET_PATH=/home/pi/
readonly TARGET_ARCH=arm-unknown-linux-gnueabi
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/airq

cargo build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}